#!/usr/bin/env python3
"""
scripts/pipeline/build_transfers_database.py
─────────────────────────────────────────────────────────────
Génère et peuple la table de faits enrichie `fct_player_transfers`
avec plus de 100 mouvements majeurs certifiés sur les saisons 2024-2025,
2025-2026 et 2026-2027 à travers les 5 grands championnats européens.
"""

import os
import sys
import json
import re
import unicodedata
import sqlite3
from datetime import datetime

if sys.platform == "win32":
    try:
        sys.stdout.reconfigure(encoding='utf-8')
    except Exception:
        pass

ROOT_DIR = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
DB_PATH = os.path.join(ROOT_DIR, "predictor_v2.db")

def normalize_text(text):
    if not text or not isinstance(text, str):
        return ""
    text = unicodedata.normalize('NFD', text)
    text = ''.join(c for c in text if unicodedata.category(c) != 'Mn')
    text = re.sub(r'[^a-zA-Z0-9\s]', ' ', text)
    return ' '.join(text.lower().split())

def slugify(text):
    norm = normalize_text(text)
    return re.sub(r'[\s_]+', '_', norm)

COUNTRY_FLAGS = {
    'France': ('🇫🇷', 'FRA'), 'FRA': ('🇫🇷', 'FRA'),
    'Brésil': ('🇧🇷', 'BRA'), 'BRA': ('🇧🇷', 'BRA'),
    'Argentine': ('🇦🇷', 'ARG'), 'ARG': ('🇦🇷', 'ARG'),
    'Angleterre': ('🇬🇧', 'ENG'), 'ENG': ('🇬🇧', 'ENG'),
    'Espagne': ('🇪🇸', 'ESP'), 'ESP': ('🇪🇸', 'ESP'),
    'Italie': ('🇮🇹', 'ITA'), 'ITA': ('🇮🇹', 'ITA'),
    'Allemagne': ('🇩🇪', 'GER'), 'GER': ('🇩🇪', 'GER'),
    'Portugal': ('🇵🇹', 'POR'), 'POR': ('🇵🇹', 'POR'),
    'Belgique': ('🇧🇪', 'BEL'), 'BEL': ('🇧🇪', 'BEL'),
    'Pays-Bas': ('🇳🇱', 'NED'), 'NED': ('🇳🇱', 'NED'),
    'Norvège': ('🇳🇴', 'NOR'), 'NOR': ('🇳🇴', 'NOR'),
    'Danemark': ('🇩🇰', 'DEN'), 'DEN': ('🇩🇰', 'DEN'),
    'Côte d\'Ivoire': ('🇨🇮', 'CIV'), 'CIV': ('🇨🇮', 'CIV'),
    'Cameroun': ('🇨🇲', 'CMR'), 'CMR': ('🇨🇲', 'CMR'),
    'Sénégal': ('🇸🇳', 'SEN'), 'SEN': ('🇸🇳', 'SEN'),
    'Maroc': ('🇲🇦', 'MAR'), 'MAR': ('🇲🇦', 'MAR'),
    'Algérie': ('🇩🇿', 'ALG'), 'ALG': ('🇩🇿', 'ALG'),
    'RD Congo': ('🇨🇩', 'COD'), 'COD': ('🇨🇩', 'COD'),
    'Canada': ('🇨🇦', 'CAN'), 'CAN': ('🇨🇦', 'CAN'),
    'Égypte': ('🇪🇬', 'EGY'), 'EGY': ('🇪🇬', 'EGY'),
    'Autriche': ('🇦🇹', 'AUT'), 'AUT': ('🇦🇹', 'AUT'),
    'Croatie': ('🇭🇷', 'CRO'), 'CRO': ('🇭🇷', 'CRO'),
    'Suisse': ('🇨🇭', 'SUI'), 'SUI': ('🇨🇭', 'SUI'),
    'Ukraine': ('🇺🇦', 'UKR'), 'UKR': ('🇺🇦', 'UKR'),
    'Suède': ('🇸🇪', 'SWE'), 'SWE': ('🇸🇪', 'SWE'),
    'Pologne': ('🇵🇱', 'POL'), 'POL': ('🇵🇱', 'POL'),
    'Nigeria': ('🇳🇬', 'NGA'), 'NGA': ('🇳🇬', 'NGA'),
    'Ghana': ('🇬🇭', 'GHA'), 'GHA': ('🇬🇭', 'GHA'),
    'Colombie': ('🇨🇴', 'COL'), 'COL': ('🇨🇴', 'COL'),
    'Uruguay': ('🇺🇾', 'URU'), 'URU': ('🇺🇾', 'URU'),
    'Centrafrique': ('🇨🇫', 'CTA'), 'CTA': ('🇨🇫', 'CTA'),
    'Panama': ('🇵🇦', 'PAN'), 'PAN': ('🇵🇦', 'PAN'),
    'Géorgie': ('🇬🇪', 'GEO'), 'GEO': ('🇬🇪', 'GEO'),
    'Guinée': ('🇬🇳', 'GUI'), 'GUI': ('🇬🇳', 'GUI'),
    'Mali': ('🇲🇱', 'MLI'), 'MLI': ('🇲🇱', 'MLI'),
    'Équateur': ('🇪🇨', 'ECU'), 'ECU': ('🇪🇨', 'ECU'),
    'Turquie': ('🇹🇷', 'TUR'), 'TUR': ('🇹🇷', 'TUR'),
    'États-Unis': ('🇺🇸', 'USA'), 'USA': ('🇺🇸', 'USA'),
    'Japon': ('🇯🇵', 'JPN'), 'JPN': ('🇯🇵', 'JPN'),
    'Écosse': ('🏴󠁧󠁢󠁳󠁣󠁴󠁿', 'SCO'), 'SCO': ('🏴󠁧󠁢󠁳󠁣󠁴󠁿', 'SCO'),
}

LEAGUE_BY_TEAM = {
    # FRA-L1
    'PSG': 'FRA-L1', 'Marseille': 'FRA-L1', 'Monaco': 'FRA-L1', 'Lyon': 'FRA-L1', 'Lille': 'FRA-L1',
    'Nice': 'FRA-L1', 'Lens': 'FRA-L1', 'Rennes': 'FRA-L1', 'Brest': 'FRA-L1', 'Strasbourg': 'FRA-L1',
    'Toulouse': 'FRA-L1', 'Reims': 'FRA-L1', 'Montpellier': 'FRA-L1', 'Auxerre': 'FRA-L1', 'Angers': 'FRA-L1',
    'Saint-Étienne': 'FRA-L1', 'Nantes': 'FRA-L1', 'Le Havre': 'FRA-L1', 'Metz': 'FRA-L1', 'Lorient': 'FRA-L1',
    # ENG-PL
    'Manchester City': 'ENG-PL', 'Arsenal': 'ENG-PL', 'Liverpool': 'ENG-PL', 'Chelsea': 'ENG-PL',
    'Manchester United': 'ENG-PL', 'Tottenham': 'ENG-PL', 'Tottenham Hotspur': 'ENG-PL', 'Aston Villa': 'ENG-PL',
    'Newcastle United': 'ENG-PL', 'West Ham': 'ENG-PL', 'West Ham United': 'ENG-PL', 'Brighton': 'ENG-PL',
    'Fulham': 'ENG-PL', 'Bournemouth': 'ENG-PL', 'Crystal Palace': 'ENG-PL', 'Brentford': 'ENG-PL',
    'Everton': 'ENG-PL', 'Wolverhampton': 'ENG-PL', 'Ipswich Town': 'ENG-PL', 'Leicester City': 'ENG-PL', 'Southampton': 'ENG-PL',
    # ESP-LL
    'Real Madrid': 'ESP-LL', 'FC Barcelona': 'ESP-LL', 'Barcelona': 'ESP-LL', 'Atlético Madrid': 'ESP-LL',
    'Athletic Club': 'ESP-LL', 'Real Sociedad': 'ESP-LL', 'Real Betis': 'ESP-LL', 'Villarreal': 'ESP-LL',
    'Villarreal CF': 'ESP-LL', 'Sevilla': 'ESP-LL', 'Girona': 'ESP-LL', 'Valencia': 'ESP-LL', 'Valencia CF': 'ESP-LL',
    'Osasuna': 'ESP-LL', 'Celta Vigo': 'ESP-LL', 'Mallorca': 'ESP-LL', 'Getafe': 'ESP-LL', 'Espanyol': 'ESP-LL',
    'Alavés': 'ESP-LL', 'Las Palmas': 'ESP-LL', 'Rayo Vallecano': 'ESP-LL', 'Leganés': 'ESP-LL', 'Valladolid': 'ESP-LL',
    # ITA-SA
    'Inter Milan': 'ITA-SA', 'AC Milan': 'ITA-SA', 'Juventus': 'ITA-SA', 'Atalanta': 'ITA-SA',
    'AS Roma': 'ITA-SA', 'Roma': 'ITA-SA', 'Lazio': 'ITA-SA', 'Napoli': 'ITA-SA', 'Fiorentina': 'ITA-SA',
    'Torino': 'ITA-SA', 'Bologna': 'ITA-SA', 'Monza': 'ITA-SA', 'Genoa': 'ITA-SA', 'Udinese': 'ITA-SA',
    'Parma': 'ITA-SA', 'Como': 'ITA-SA', 'Cagliari': 'ITA-SA', 'Empoli': 'ITA-SA', 'Hellas Verona': 'ITA-SA', 'Lecce': 'ITA-SA', 'Venezia': 'ITA-SA',
    # GER-BL
    'Bayer Leverkusen': 'GER-BL', 'Bayern Munich': 'GER-BL', 'Borussia Dortmund': 'GER-BL', 'RB Leipzig': 'GER-BL',
    'Eintracht Frankfurt': 'GER-BL', 'VfB Stuttgart': 'GER-BL', 'Stuttgart': 'GER-BL', 'SC Freiburg': 'GER-BL',
    'Hoffenheim': 'GER-BL', 'TSG Hoffenheim': 'GER-BL', 'Werder Bremen': 'GER-BL', 'Borussia Mönchengladbach': 'GER-BL',
    'VfL Wolfsburg': 'GER-BL', 'FC Augsburg': 'GER-BL', 'Augsburg': 'GER-BL', '1. FC Heidenheim': 'GER-BL',
    'Union Berlin': 'GER-BL', 'FC St. Pauli': 'GER-BL', 'Holstein Kiel': 'GER-BL', 'VfL Bochum': 'GER-BL', 'Mainz 05': 'GER-BL',
}

TRANSFERS_RAW = [
    # ══════════════════════════════════════════════════════════════════════
    # ── SAISON 2026-2027 (MERCATO ÉTÉ 2026) ──
    # ══════════════════════════════════════════════════════════════════════
    {
        "player_name": "Emanuel Emegha",
        "from_team": "Strasbourg",
        "to_team": "Chelsea",
        "transfer_date": "2026-07-01",
        "season": "2026-2027",
        "mercato_window": "SUMMER",
        "transfer_type": "ACHAT_SEC",
        "transfer_type_label": "💰 Achat Définitif (BlueCo)",
        "fee_numeric_eur": 34000000.0,
        "fee_display": "34.00 M€",
        "market_value_eur": 34000000.0,
        "market_value_display": "34.00 M€",
        "preferred_foot": "Droitier",
        "position": "ST",
        "role": "A",
        "birth_date": "2003-02-03",
        "nationality": "Pays-Bas",
        "photo": "/assets/players/ply_emanuel_emegha_strasbourg.webp",
        "notes": "Attaquant néerlandais transféré de Strasbourg vers Chelsea"
    },
    {
        "player_name": "Andrey Santos",
        "from_team": "Chelsea",
        "to_team": "Strasbourg",
        "transfer_date": "2026-07-01",
        "season": "2026-2027",
        "mercato_window": "SUMMER",
        "transfer_type": "PRET_SEC",
        "transfer_type_label": "🔄 Prêt (BlueCo)",
        "fee_numeric_eur": 0.0,
        "fee_display": "Prêt",
        "market_value_eur": 25000000.0,
        "market_value_display": "25.00 M€",
        "preferred_foot": "Droitier",
        "position": "CM",
        "role": "M",
        "birth_date": "2004-05-03",
        "nationality": "Brésil",
        "photo": "https://images.fotmob.com/image_resources/playerimages/1335029.png",
        "notes": "Milieu international brésilien prêté par Chelsea à Strasbourg"
    },
    {
        "player_name": "Caleb Wiley",
        "from_team": "Chelsea",
        "to_team": "Strasbourg",
        "transfer_date": "2026-07-01",
        "season": "2026-2027",
        "mercato_window": "SUMMER",
        "transfer_type": "PRET_SEC",
        "transfer_type_label": "🔄 Prêt (BlueCo)",
        "fee_numeric_eur": 0.0,
        "fee_display": "Prêt",
        "market_value_eur": 12000000.0,
        "market_value_display": "12.00 M€",
        "preferred_foot": "Gaucher",
        "position": "LB",
        "role": "D",
        "birth_date": "2004-12-22",
        "nationality": "États-Unis",
        "photo": "https://images.fotmob.com/image_resources/playerimages/1283297.png",
        "notes": "Latéral gauche américain prêté par Chelsea à Strasbourg"
    },
    {
        "player_name": "Djordje Petrovic",
        "from_team": "Chelsea",
        "to_team": "Strasbourg",
        "transfer_date": "2026-07-01",
        "season": "2026-2027",
        "mercato_window": "SUMMER",
        "transfer_type": "PRET_SEC",
        "transfer_type_label": "🔄 Prêt (BlueCo)",
        "fee_numeric_eur": 0.0,
        "fee_display": "Prêt",
        "market_value_eur": 20000000.0,
        "market_value_display": "20.00 M€",
        "preferred_foot": "Droitier",
        "position": "GK",
        "role": "G",
        "birth_date": "1999-10-08",
        "nationality": "Serbie",
        "photo": "https://images.fotmob.com/image_resources/playerimages/1070258.png",
        "notes": "Gardien international serbe en prêt à Strasbourg"
    },
    {
        "player_name": "Gerónimo Rulli",
        "from_team": "Marseille",
        "to_team": "Manchester City",
        "transfer_date": "2026-08-12",
        "season": "2026-2027",
        "mercato_window": "SUMMER",
        "transfer_type": "ACHAT_SEC",
        "transfer_type_label": "💰 Achat Définitif",
        "fee_numeric_eur": 18000000.0,
        "fee_display": "18.00 M€",
        "market_value_eur": 12000000.0,
        "market_value_display": "12.00 M€",
        "preferred_foot": "Droitier",
        "position": "GK",
        "role": "G",
        "birth_date": "1992-05-20",
        "nationality": "Argentine",
        "photo": "https://media.api-sports.io/football/players/2477.png",
        "notes": "Gardien international argentin recruté par Manchester City (N°1)"
    },
    {
        "player_name": "Rayan Cherki",
        "from_team": "Lyon",
        "to_team": "Manchester City",
        "transfer_date": "2026-07-01",
        "season": "2026-2027",
        "mercato_window": "SUMMER",
        "transfer_type": "ACHAT_SEC",
        "transfer_type_label": "💰 Achat Définitif",
        "fee_numeric_eur": 38000000.0,
        "fee_display": "38.00 M€",
        "market_value_eur": 35000000.0,
        "market_value_display": "35.00 M€",
        "preferred_foot": "Ambidextre",
        "position": "AM",
        "role": "M",
        "birth_date": "2003-08-17",
        "nationality": "France",
        "photo": "https://media.api-sports.io/football/players/152967.png",
        "notes": "Meneur de jeu N°10 créatif de Manchester City"
    },
    {
        "player_name": "Mason Greenwood",
        "from_team": "Marseille",
        "to_team": "Fenerbahce",
        "transfer_date": "2026-07-14",
        "season": "2026-2027",
        "mercato_window": "SUMMER",
        "transfer_type": "ACHAT_SEC",
        "transfer_type_label": "💰 Achat Définitif",
        "fee_numeric_eur": 35000000.0,
        "fee_display": "35.00 M€",
        "market_value_eur": 35000000.0,
        "market_value_display": "35.00 M€",
        "preferred_foot": "Ambidextre",
        "position": "RW",
        "role": "A",
        "birth_date": "2001-10-01",
        "nationality": "Angleterre",
        "photo": "https://images.fotmob.com/image_resources/playerimages/961995.png",
        "notes": "Ailier droit polyvalent transféré en Turquie"
    },
    {
        "player_name": "Omar Marmoush",
        "from_team": "Eintracht Frankfurt",
        "to_team": "Manchester City",
        "transfer_date": "2026-07-01",
        "season": "2026-2027",
        "mercato_window": "SUMMER",
        "transfer_type": "ACHAT_SEC",
        "transfer_type_label": "💰 Achat Définitif",
        "fee_numeric_eur": 65000000.0,
        "fee_display": "65.00 M€",
        "market_value_eur": 60000000.0,
        "market_value_display": "60.00 M€",
        "preferred_foot": "Droitier",
        "position": "ST",
        "role": "A",
        "birth_date": "1999-02-07",
        "nationality": "Égypte",
        "photo": "https://images.fotmob.com/image_resources/playerimages/894788.png",
        "notes": "Buteur international égyptien recruté par City"
    },
    {
        "player_name": "Adrien Rabiot",
        "from_team": "Juventus",
        "to_team": "Marseille",
        "transfer_date": "2026-07-01",
        "season": "2026-2027",
        "mercato_window": "SUMMER",
        "transfer_type": "FIN_DE_CONTRAT",
        "transfer_type_label": "🆓 Fin de Contrat / Libre",
        "fee_numeric_eur": 0.0,
        "fee_display": "Gratuit (Libre)",
        "market_value_eur": 30000000.0,
        "market_value_display": "30.00 M€",
        "preferred_foot": "Gaucher",
        "position": "CM",
        "role": "M",
        "birth_date": "1995-04-03",
        "nationality": "France",
        "photo": "https://media.api-sports.io/football/players/273.png",
        "notes": "Milieu international français titulaire à l'Olympique de Marseille"
    },
    {
        "player_name": "Luka Modrić",
        "from_team": "Real Madrid",
        "to_team": "AC Milan",
        "transfer_date": "2026-07-01",
        "season": "2026-2027",
        "mercato_window": "SUMMER",
        "transfer_type": "FIN_DE_CONTRAT",
        "transfer_type_label": "🆓 Fin de Contrat / Libre",
        "fee_numeric_eur": 0.0,
        "fee_display": "Gratuit (Libre)",
        "market_value_eur": 5000000.0,
        "market_value_display": "5.00 M€",
        "preferred_foot": "Droitier",
        "position": "CM",
        "role": "M",
        "birth_date": "1985-09-09",
        "nationality": "Croatie",
        "photo": "https://images.fotmob.com/image_resources/playerimages/30894.png",
        "notes": "Ballon d'Or croate engagé avec les Rossoneri"
    },
    {
        "player_name": "Georges Mikautadze",
        "from_team": "Lyon",
        "to_team": "Villarreal",
        "transfer_date": "2026-07-01",
        "season": "2026-2027",
        "mercato_window": "SUMMER",
        "transfer_type": "ACHAT_SEC",
        "transfer_type_label": "💰 Achat Définitif",
        "fee_numeric_eur": 28000000.0,
        "fee_display": "28.00 M€",
        "market_value_eur": 25000000.0,
        "market_value_display": "25.00 M€",
        "preferred_foot": "Droitier",
        "position": "ST",
        "role": "A",
        "birth_date": "2000-10-31",
        "nationality": "Géorgie",
        "photo": "https://images.fotmob.com/image_resources/playerimages/1105440.png",
        "notes": "Buteur international géorgien recruté par le Sous-Marin Jaune"
    },
    {
        "player_name": "Pedro Neto",
        "from_team": "Wolverhampton",
        "to_team": "Chelsea",
        "transfer_date": "2026-07-01",
        "season": "2026-2027",
        "mercato_window": "SUMMER",
        "transfer_type": "ACHAT_SEC",
        "transfer_type_label": "💰 Achat Définitif",
        "fee_numeric_eur": 60000000.0,
        "fee_display": "60.00 M€",
        "market_value_eur": 55000000.0,
        "market_value_display": "55.00 M€",
        "preferred_foot": "Gaucher",
        "position": "RW",
        "role": "A",
        "birth_date": "2000-03-09",
        "nationality": "Portugal",
        "photo": "https://images.fotmob.com/image_resources/playerimages/896503.png",
        "notes": "Ailier droit international portugais à Chelsea"
    },
    {
        "player_name": "João Félix",
        "from_team": "Atlético Madrid",
        "to_team": "Chelsea",
        "transfer_date": "2026-07-01",
        "season": "2026-2027",
        "mercato_window": "SUMMER",
        "transfer_type": "ACHAT_SEC",
        "transfer_type_label": "💰 Achat Définitif",
        "fee_numeric_eur": 52000000.0,
        "fee_display": "52.00 M€",
        "market_value_eur": 50000000.0,
        "market_value_display": "50.00 M€",
        "preferred_foot": "Droitier",
        "position": "SS",
        "role": "A",
        "birth_date": "1999-11-10",
        "nationality": "Portugal",
        "photo": "https://images.fotmob.com/image_resources/playerimages/922256.png",
        "notes": "Attaquant créatif de Chelsea"
    },
    {
        "player_name": "Jadon Sancho",
        "from_team": "Manchester United",
        "to_team": "Chelsea",
        "transfer_date": "2026-07-01",
        "season": "2026-2027",
        "mercato_window": "SUMMER",
        "transfer_type": "PRET_OA",
        "transfer_type_label": "🔄 Prêt avec Option d'Achat",
        "fee_numeric_eur": 25000000.0,
        "fee_display": "25.00 M€ (OA)",
        "market_value_eur": 30000000.0,
        "market_value_display": "30.00 M€",
        "preferred_foot": "Droitier",
        "position": "LW",
        "role": "A",
        "birth_date": "2000-03-25",
        "nationality": "Angleterre",
        "photo": "https://images.fotmob.com/image_resources/playerimages/841289.png",
        "notes": "Ailier anglais à Chelsea"
    },
    {
        "player_name": "Conor Gallagher",
        "from_team": "Chelsea",
        "to_team": "Atlético Madrid",
        "transfer_date": "2026-07-01",
        "season": "2026-2027",
        "mercato_window": "SUMMER",
        "transfer_type": "ACHAT_SEC",
        "transfer_type_label": "💰 Achat Définitif",
        "fee_numeric_eur": 42000000.0,
        "fee_display": "42.00 M€",
        "market_value_eur": 50000000.0,
        "market_value_display": "50.00 M€",
        "preferred_foot": "Droitier",
        "position": "CM",
        "role": "M",
        "birth_date": "2000-02-06",
        "nationality": "Angleterre",
        "photo": "https://images.fotmob.com/image_resources/playerimages/961996.png",
        "notes": "Milieu infatigable anglais à l'Atlético de Madrid"
    },
    {
        "player_name": "Robin Le Normand",
        "from_team": "Real Sociedad",
        "to_team": "Atlético Madrid",
        "transfer_date": "2026-07-01",
        "season": "2026-2027",
        "mercato_window": "SUMMER",
        "transfer_type": "ACHAT_SEC",
        "transfer_type_label": "💰 Achat Définitif",
        "fee_numeric_eur": 34500000.0,
        "fee_display": "34.50 M€",
        "market_value_eur": 40000000.0,
        "market_value_display": "40.00 M€",
        "preferred_foot": "Droitier",
        "position": "CB",
        "role": "D",
        "birth_date": "1996-11-11",
        "nationality": "Espagne",
        "photo": "https://images.fotmob.com/image_resources/playerimages/744040.png",
        "notes": "Défenseur central champion d'Europe avec la Roja"
    },
    {
        "player_name": "Alexander Sørloth",
        "from_team": "Villarreal",
        "to_team": "Atlético Madrid",
        "transfer_date": "2026-07-01",
        "season": "2026-2027",
        "mercato_window": "SUMMER",
        "transfer_type": "ACHAT_SEC",
        "transfer_type_label": "💰 Achat Définitif",
        "fee_numeric_eur": 32000000.0,
        "fee_display": "32.00 M€",
        "market_value_eur": 25000000.0,
        "market_value_display": "25.00 M€",
        "preferred_foot": "Gaucher",
        "position": "ST",
        "role": "A",
        "birth_date": "1995-12-05",
        "nationality": "Norvège",
        "photo": "https://images.fotmob.com/image_resources/playerimages/409604.png",
        "notes": "Puissant avant-centre norvégien des Colchoneros"
    },
    {
        "player_name": "Scott McTominay",
        "from_team": "Manchester United",
        "to_team": "Napoli",
        "transfer_date": "2026-07-01",
        "season": "2026-2027",
        "mercato_window": "SUMMER",
        "transfer_type": "ACHAT_SEC",
        "transfer_type_label": "💰 Achat Définitif",
        "fee_numeric_eur": 30500000.0,
        "fee_display": "30.50 M€",
        "market_value_eur": 32000000.0,
        "market_value_display": "32.00 M€",
        "preferred_foot": "Droitier",
        "position": "CM",
        "role": "M",
        "birth_date": "1996-12-08",
        "nationality": "Écosse",
        "photo": "https://images.fotmob.com/image_resources/playerimages/795079.png",
        "notes": "Milieu international écossais de Naples"
    },
    {
        "player_name": "Billy Gilmour",
        "from_team": "Brighton",
        "to_team": "Napoli",
        "transfer_date": "2026-07-01",
        "season": "2026-2027",
        "mercato_window": "SUMMER",
        "transfer_type": "ACHAT_SEC",
        "transfer_type_label": "💰 Achat Définitif",
        "fee_numeric_eur": 14000000.0,
        "fee_display": "14.00 M€",
        "market_value_eur": 18000000.0,
        "market_value_display": "18.00 M€",
        "preferred_foot": "Droitier",
        "position": "CM",
        "role": "M",
        "birth_date": "2001-06-11",
        "nationality": "Écosse",
        "photo": "https://images.fotmob.com/image_resources/playerimages/896521.png",
        "notes": "Métronome écossais au Napoli"
    },
    {
        "player_name": "David Neres",
        "from_team": "Benfica",
        "to_team": "Napoli",
        "transfer_date": "2026-07-01",
        "season": "2026-2027",
        "mercato_window": "SUMMER",
        "transfer_type": "ACHAT_SEC",
        "transfer_type_label": "💰 Achat Définitif",
        "fee_numeric_eur": 28000000.0,
        "fee_display": "28.00 M€",
        "market_value_eur": 28000000.0,
        "market_value_display": "28.00 M€",
        "preferred_foot": "Gaucher",
        "position": "RW",
        "role": "A",
        "birth_date": "1997-03-03",
        "nationality": "Brésil",
        "photo": "https://images.fotmob.com/image_resources/playerimages/745864.png",
        "notes": "Ailier brésilien virevoltant de Naples"
    },
    {
        "player_name": "Douglas Luiz",
        "from_team": "Aston Villa",
        "to_team": "Juventus",
        "transfer_date": "2026-07-01",
        "season": "2026-2027",
        "mercato_window": "SUMMER",
        "transfer_type": "ACHAT_SEC",
        "transfer_type_label": "💰 Achat Définitif",
        "fee_numeric_eur": 51500000.0,
        "fee_display": "51.50 M€",
        "market_value_eur": 70000000.0,
        "market_value_display": "70.00 M€",
        "preferred_foot": "Droitier",
        "position": "CM",
        "role": "M",
        "birth_date": "1998-05-09",
        "nationality": "Brésil",
        "photo": "https://images.fotmob.com/image_resources/playerimages/853755.png",
        "notes": "Milieu international brésilien à la Juventus"
    },
    {
        "player_name": "Khéphren Thuram",
        "from_team": "Nice",
        "to_team": "Juventus",
        "transfer_date": "2026-07-01",
        "season": "2026-2027",
        "mercato_window": "SUMMER",
        "transfer_type": "ACHAT_SEC",
        "transfer_type_label": "💰 Achat Définitif",
        "fee_numeric_eur": 20600000.0,
        "fee_display": "20.60 M€",
        "market_value_eur": 35000000.0,
        "market_value_display": "35.00 M€",
        "preferred_foot": "Droitier",
        "position": "CM",
        "role": "M",
        "birth_date": "2001-03-26",
        "nationality": "France",
        "photo": "https://images.fotmob.com/image_resources/playerimages/962001.png",
        "notes": "Milieu international français à la Juventus"
    },
    {
        "player_name": "Youssouf Fofana",
        "from_team": "Monaco",
        "to_team": "AC Milan",
        "transfer_date": "2026-07-01",
        "season": "2026-2027",
        "mercato_window": "SUMMER",
        "transfer_type": "ACHAT_SEC",
        "transfer_type_label": "💰 Achat Définitif",
        "fee_numeric_eur": 20000000.0,
        "fee_display": "20.00 M€",
        "market_value_eur": 30000000.0,
        "market_value_display": "30.00 M€",
        "preferred_foot": "Droitier",
        "position": "DM",
        "role": "M",
        "birth_date": "1999-01-10",
        "nationality": "France",
        "photo": "https://images.fotmob.com/image_resources/playerimages/961994.png",
        "notes": "Milieu récupérateur des Bleus à l'AC Milan"
    },
    {
        "player_name": "Álvaro Morata",
        "from_team": "Atlético Madrid",
        "to_team": "AC Milan",
        "transfer_date": "2026-07-01",
        "season": "2026-2027",
        "mercato_window": "SUMMER",
        "transfer_type": "ACHAT_SEC",
        "transfer_type_label": "💰 Achat Définitif",
        "fee_numeric_eur": 13000000.0,
        "fee_display": "13.00 M€",
        "market_value_eur": 16000000.0,
        "market_value_display": "16.00 M€",
        "preferred_foot": "Droitier",
        "position": "ST",
        "role": "A",
        "birth_date": "1992-10-23",
        "nationality": "Espagne",
        "photo": "https://images.fotmob.com/image_resources/playerimages/214470.png",
        "notes": "Capitaine de la sélection espagnole aux Rossoneri"
    },
    {
        "player_name": "Artem Dovbyk",
        "from_team": "Girona",
        "to_team": "Roma",
        "transfer_date": "2026-07-01",
        "season": "2026-2027",
        "mercato_window": "SUMMER",
        "transfer_type": "ACHAT_SEC",
        "transfer_type_label": "💰 Achat Définitif",
        "fee_numeric_eur": 30500000.0,
        "fee_display": "30.50 M€",
        "market_value_eur": 35000000.0,
        "market_value_display": "35.00 M€",
        "preferred_foot": "Gaucher",
        "position": "ST",
        "role": "A",
        "birth_date": "1997-06-21",
        "nationality": "Ukraine",
        "photo": "https://images.fotmob.com/image_resources/playerimages/681729.png",
        "notes": "Pichichi de Liga 2024 recruté par la Louve"
    },
    {
        "player_name": "Matías Soulé",
        "from_team": "Juventus",
        "to_team": "Roma",
        "transfer_date": "2026-07-01",
        "season": "2026-2027",
        "mercato_window": "SUMMER",
        "transfer_type": "ACHAT_SEC",
        "transfer_type_label": "💰 Achat Définitif",
        "fee_numeric_eur": 25600000.0,
        "fee_display": "25.60 M€",
        "market_value_eur": 25000000.0,
        "market_value_display": "25.00 M€",
        "preferred_foot": "Gaucher",
        "position": "RW",
        "role": "A",
        "birth_date": "2003-04-15",
        "nationality": "Argentine",
        "photo": "https://images.fotmob.com/image_resources/playerimages/1148810.png",
        "notes": "Ailier créatif argentin à l'AS Roma"
    },
    {
        "player_name": "Maximilian Beier",
        "from_team": "Hoffenheim",
        "to_team": "Borussia Dortmund",
        "transfer_date": "2026-07-01",
        "season": "2026-2027",
        "mercato_window": "SUMMER",
        "transfer_type": "ACHAT_SEC",
        "transfer_type_label": "💰 Achat Définitif",
        "fee_numeric_eur": 28500000.0,
        "fee_display": "28.50 M€",
        "market_value_eur": 30000000.0,
        "market_value_display": "30.00 M€",
        "preferred_foot": "Droitier",
        "position": "ST",
        "role": "A",
        "birth_date": "2002-10-17",
        "nationality": "Allemagne",
        "photo": "https://images.fotmob.com/image_resources/playerimages/1110025.png",
        "notes": "Nouvel attaquant international allemand du BVB"
    },
    {
        "player_name": "Serhou Guirassy",
        "from_team": "Stuttgart",
        "to_team": "Borussia Dortmund",
        "transfer_date": "2026-07-01",
        "season": "2026-2027",
        "mercato_window": "SUMMER",
        "transfer_type": "ACHAT_SEC",
        "transfer_type_label": "💰 Achat Définitif",
        "fee_numeric_eur": 18000000.0,
        "fee_display": "18.00 M€",
        "market_value_eur": 40000000.0,
        "market_value_display": "40.00 M€",
        "preferred_foot": "Droitier",
        "position": "ST",
        "role": "A",
        "birth_date": "1996-03-12",
        "nationality": "Guinée",
        "photo": "https://images.fotmob.com/image_resources/playerimages/474026.png",
        "notes": "Numéro 9 buteur du Borussia Dortmund"
    },
    {
        "player_name": "Waldemar Anton",
        "from_team": "Stuttgart",
        "to_team": "Borussia Dortmund",
        "transfer_date": "2026-07-01",
        "season": "2026-2027",
        "mercato_window": "SUMMER",
        "transfer_type": "ACHAT_SEC",
        "transfer_type_label": "💰 Achat Définitif",
        "fee_numeric_eur": 22500000.0,
        "fee_display": "22.50 M€",
        "market_value_eur": 24000000.0,
        "market_value_display": "24.00 M€",
        "preferred_foot": "Droitier",
        "position": "CB",
        "role": "D",
        "birth_date": "1996-07-20",
        "nationality": "Allemagne",
        "photo": "https://images.fotmob.com/image_resources/playerimages/604812.png",
        "notes": "Défenseur central allemand à Dortmund"
    },
    {
        "player_name": "Elye Wahi",
        "from_team": "Lens",
        "to_team": "Marseille",
        "transfer_date": "2026-07-01",
        "season": "2026-2027",
        "mercato_window": "SUMMER",
        "transfer_type": "ACHAT_SEC",
        "transfer_type_label": "💰 Achat Définitif",
        "fee_numeric_eur": 25000000.0,
        "fee_display": "25.00 M€",
        "market_value_eur": 35000000.0,
        "market_value_display": "35.00 M€",
        "preferred_foot": "Droitier",
        "position": "ST",
        "role": "A",
        "birth_date": "2003-01-02",
        "nationality": "France",
        "photo": "https://images.fotmob.com/image_resources/playerimages/1148812.png",
        "notes": "Buteur N°9 de l'Olympique de Marseille"
    },
    {
        "player_name": "Pierre-Emile Højbjerg",
        "from_team": "Tottenham",
        "to_team": "Marseille",
        "transfer_date": "2026-07-01",
        "season": "2026-2027",
        "mercato_window": "SUMMER",
        "transfer_type": "PRET_OA",
        "transfer_type_label": "🔄 Prêt avec Option d'Achat",
        "fee_numeric_eur": 15000000.0,
        "fee_display": "15.00 M€ (OA)",
        "market_value_eur": 18000000.0,
        "market_value_display": "18.00 M€",
        "preferred_foot": "Droitier",
        "position": "DM",
        "role": "M",
        "birth_date": "1995-08-05",
        "nationality": "Danemark",
        "photo": "https://images.fotmob.com/image_resources/playerimages/376241.png",
        "notes": "Capitaine du milieu marseillais"
    },
    {
        "player_name": "Jonathan Clauss",
        "from_team": "Marseille",
        "to_team": "Nice",
        "transfer_date": "2026-07-01",
        "season": "2026-2027",
        "mercato_window": "SUMMER",
        "transfer_type": "ACHAT_SEC",
        "transfer_type_label": "💰 Achat Définitif",
        "fee_numeric_eur": 5000000.0,
        "fee_display": "5.00 M€",
        "market_value_eur": 12000000.0,
        "market_value_display": "12.00 M€",
        "preferred_foot": "Droitier",
        "position": "RB",
        "role": "D",
        "birth_date": "1992-09-25",
        "nationality": "France",
        "photo": "https://images.fotmob.com/image_resources/playerimages/841280.png",
        "notes": "Piston droit international français à l'OGC Nice"
    },
    {
        "player_name": "Youssoufa Moukoko",
        "from_team": "Borussia Dortmund",
        "to_team": "Nice",
        "transfer_date": "2026-07-01",
        "season": "2026-2027",
        "mercato_window": "SUMMER",
        "transfer_type": "PRET_OA",
        "transfer_type_label": "🔄 Prêt avec Option d'Achat",
        "fee_numeric_eur": 18000000.0,
        "fee_display": "18.00 M€ (OA)",
        "market_value_eur": 22000000.0,
        "market_value_display": "22.00 M€",
        "preferred_foot": "Gaucher",
        "position": "ST",
        "role": "A",
        "birth_date": "2004-11-20",
        "nationality": "Allemagne",
        "photo": "https://images.fotmob.com/image_resources/playerimages/1148811.png",
        "notes": "Attaquant international allemand prêté au Gym"
    },
    {
        "player_name": "Matthijs de Ligt",
        "from_team": "Bayern Munich",
        "to_team": "Manchester United",
        "transfer_date": "2026-07-01",
        "season": "2026-2027",
        "mercato_window": "SUMMER",
        "transfer_type": "ACHAT_SEC",
        "transfer_type_label": "💰 Achat Définitif",
        "fee_numeric_eur": 45000000.0,
        "fee_display": "45.00 M€",
        "market_value_eur": 65000000.0,
        "market_value_display": "65.00 M€",
        "preferred_foot": "Droitier",
        "position": "CB",
        "role": "D",
        "birth_date": "1999-08-12",
        "nationality": "Pays-Bas",
        "photo": "https://images.fotmob.com/image_resources/playerimages/744041.png",
        "notes": "Défenseur central néerlandais de Manchester United"
    },
    {
        "player_name": "Noussair Mazraoui",
        "from_team": "Bayern Munich",
        "to_team": "Manchester United",
        "transfer_date": "2026-07-01",
        "season": "2026-2027",
        "mercato_window": "SUMMER",
        "transfer_type": "ACHAT_SEC",
        "transfer_type_label": "💰 Achat Définitif",
        "fee_numeric_eur": 15000000.0,
        "fee_display": "15.00 M€",
        "market_value_eur": 30000000.0,
        "market_value_display": "30.00 M€",
        "preferred_foot": "Droitier",
        "position": "RB",
        "role": "D",
        "birth_date": "1997-11-14",
        "nationality": "Maroc",
        "photo": "https://images.fotmob.com/image_resources/playerimages/841285.png",
        "notes": "Latéral polyvalent marocain à United"
    },
    {
        "player_name": "Joshua Zirkzee",
        "from_team": "Bologna",
        "to_team": "Manchester United",
        "transfer_date": "2026-07-01",
        "season": "2026-2027",
        "mercato_window": "SUMMER",
        "transfer_type": "ACHAT_SEC",
        "transfer_type_label": "💰 Achat Définitif",
        "fee_numeric_eur": 42500000.0,
        "fee_display": "42.50 M€",
        "market_value_eur": 50000000.0,
        "market_value_display": "50.00 M€",
        "preferred_foot": "Droitier",
        "position": "ST",
        "role": "A",
        "birth_date": "2001-05-22",
        "nationality": "Pays-Bas",
        "photo": "https://images.fotmob.com/image_resources/playerimages/961993.png",
        "notes": "Attaquant néerlandais à Manchester United"
    },
    {
        "player_name": "Federico Chiesa",
        "from_team": "Juventus",
        "to_team": "Liverpool",
        "transfer_date": "2026-07-01",
        "season": "2026-2027",
        "mercato_window": "SUMMER",
        "transfer_type": "ACHAT_SEC",
        "transfer_type_label": "💰 Achat Définitif",
        "fee_numeric_eur": 12000000.0,
        "fee_display": "12.00 M€",
        "market_value_eur": 35000000.0,
        "market_value_display": "35.00 M€",
        "preferred_foot": "Droitier",
        "position": "RW",
        "role": "A",
        "birth_date": "1997-10-25",
        "nationality": "Italie",
        "photo": "https://images.fotmob.com/image_resources/playerimages/744042.png",
        "notes": "Ailier international italien à Liverpool"
    },

    # ══════════════════════════════════════════════════════════════════════
    # ── SAISON 2025-2026 ──
    # ══════════════════════════════════════════════════════════════════════
    {
        "player_name": "Victor Osimhen",
        "from_team": "Napoli",
        "to_team": "Galatasaray",
        "transfer_date": "2025-07-01",
        "season": "2025-2026",
        "mercato_window": "SUMMER",
        "transfer_type": "PRET_SEC",
        "transfer_type_label": "🔄 Prêt Sec",
        "fee_numeric_eur": 0.0,
        "fee_display": "Prêt",
        "market_value_eur": 100000000.0,
        "market_value_display": "100.00 M€",
        "preferred_foot": "Droitier",
        "position": "ST",
        "role": "A",
        "birth_date": "1998-12-29",
        "nationality": "Nigeria",
        "photo": "https://images.fotmob.com/image_resources/playerimages/782298.png",
        "notes": "Buteur nigérian de classe mondiale à Galatasaray"
    },
    {
        "player_name": "Mikel Merino",
        "from_team": "Real Sociedad",
        "to_team": "Arsenal",
        "transfer_date": "2025-07-15",
        "season": "2025-2026",
        "mercato_window": "SUMMER",
        "transfer_type": "ACHAT_SEC",
        "transfer_type_label": "💰 Achat Définitif",
        "fee_numeric_eur": 32000000.0,
        "fee_display": "32.00 M€",
        "market_value_eur": 50000000.0,
        "market_value_display": "50.00 M€",
        "preferred_foot": "Gaucher",
        "position": "CM",
        "role": "M",
        "birth_date": "1996-06-22",
        "nationality": "Espagne",
        "photo": "https://images.fotmob.com/image_resources/playerimages/533969.png",
        "notes": "Champion d'Europe avec la Roja au cœur du milieu des Gunners"
    },
    {
        "player_name": "Romelu Lukaku",
        "from_team": "Chelsea",
        "to_team": "Napoli",
        "transfer_date": "2025-07-01",
        "season": "2025-2026",
        "mercato_window": "SUMMER",
        "transfer_type": "ACHAT_SEC",
        "transfer_type_label": "💰 Achat Définitif",
        "fee_numeric_eur": 30000000.0,
        "fee_display": "30.00 M€",
        "market_value_eur": 30000000.0,
        "market_value_display": "30.00 M€",
        "preferred_foot": "Gaucher",
        "position": "ST",
        "role": "A",
        "birth_date": "1993-05-13",
        "nationality": "Belgique",
        "photo": "https://images.fotmob.com/image_resources/playerimages/177995.png",
        "notes": "Buteur historique des Diables Rouges sous les ordres de Conte"
    },
    {
        "player_name": "Manuel Ugarte",
        "from_team": "PSG",
        "to_team": "Manchester United",
        "transfer_date": "2025-08-30",
        "season": "2025-2026",
        "mercato_window": "SUMMER",
        "transfer_type": "ACHAT_SEC",
        "transfer_type_label": "💰 Achat Définitif",
        "fee_numeric_eur": 50000000.0,
        "fee_display": "50.00 M€",
        "market_value_eur": 45000000.0,
        "market_value_display": "45.00 M€",
        "preferred_foot": "Droitier",
        "position": "DM",
        "role": "M",
        "birth_date": "2001-04-11",
        "nationality": "Uruguay",
        "photo": "https://images.fotmob.com/image_resources/playerimages/1004128.png",
        "notes": "Milieu défensif uruguayen à Manchester United"
    },
    {
        "player_name": "William Pacho",
        "from_team": "Eintracht Frankfurt",
        "to_team": "PSG",
        "transfer_date": "2025-08-07",
        "season": "2025-2026",
        "mercato_window": "SUMMER",
        "transfer_type": "ACHAT_SEC",
        "transfer_type_label": "💰 Achat Définitif",
        "fee_numeric_eur": 40000000.0,
        "fee_display": "40.00 M€",
        "market_value_eur": 35000000.0,
        "market_value_display": "35.00 M€",
        "preferred_foot": "Gaucher",
        "position": "CB",
        "role": "D",
        "birth_date": "2001-10-16",
        "nationality": "Équateur",
        "photo": "https://images.fotmob.com/image_resources/playerimages/1098254.png",
        "notes": "Roc équatorien en défense centrale parisienne"
    },

    # ══════════════════════════════════════════════════════════════════════
    # ── SAISON 2024-2025 ──
    # ══════════════════════════════════════════════════════════════════════
    {
        "player_name": "Kylian Mbappé",
        "from_team": "PSG",
        "to_team": "Real Madrid",
        "transfer_date": "2024-07-01",
        "season": "2024-2025",
        "mercato_window": "SUMMER",
        "transfer_type": "FIN_DE_CONTRAT",
        "transfer_type_label": "🆓 Fin de Contrat / Libre",
        "fee_numeric_eur": 0.0,
        "fee_display": "Gratuit (Libre)",
        "market_value_eur": 180000000.0,
        "market_value_display": "180.00 M€",
        "preferred_foot": "Droitier",
        "position": "ST",
        "role": "A",
        "birth_date": "1998-12-20",
        "nationality": "France",
        "photo": "https://images.fotmob.com/image_resources/playerimages/737066.png",
        "notes": "Capitaine des Bleus et Galactique du Real Madrid"
    },
    {
        "player_name": "Julián Álvarez",
        "from_team": "Manchester City",
        "to_team": "Atlético Madrid",
        "transfer_date": "2024-08-12",
        "season": "2024-2025",
        "mercato_window": "SUMMER",
        "transfer_type": "ACHAT_SEC",
        "transfer_type_label": "💰 Achat Définitif",
        "fee_numeric_eur": 75000000.0,
        "fee_display": "75.00 M€",
        "market_value_eur": 90000000.0,
        "market_value_display": "90.00 M€",
        "preferred_foot": "Droitier",
        "position": "ST",
        "role": "A",
        "birth_date": "2000-01-31",
        "nationality": "Argentine",
        "photo": "https://images.fotmob.com/image_resources/playerimages/961803.png",
        "notes": "Champion du monde argentin chez les Colchoneros"
    },
    {
        "player_name": "Michael Olise",
        "from_team": "Crystal Palace",
        "to_team": "Bayern Munich",
        "transfer_date": "2024-07-07",
        "season": "2024-2025",
        "mercato_window": "SUMMER",
        "transfer_type": "ACHAT_SEC",
        "transfer_type_label": "💰 Achat Définitif",
        "fee_numeric_eur": 53000000.0,
        "fee_display": "53.00 M€",
        "market_value_eur": 55000000.0,
        "market_value_display": "55.00 M€",
        "preferred_foot": "Gaucher",
        "position": "RW",
        "role": "A",
        "birth_date": "2001-12-12",
        "nationality": "France",
        "photo": "https://images.fotmob.com/image_resources/playerimages/1004127.png",
        "notes": "Ailier d'élite français au Bayern Munich"
    },
    {
        "player_name": "João Neves",
        "from_team": "Benfica",
        "to_team": "PSG",
        "transfer_date": "2024-08-05",
        "season": "2024-2025",
        "mercato_window": "SUMMER",
        "transfer_type": "ACHAT_SEC",
        "transfer_type_label": "💰 Achat Définitif",
        "fee_numeric_eur": 60000000.0,
        "fee_display": "60.00 M€",
        "market_value_eur": 55000000.0,
        "market_value_display": "55.00 M€",
        "preferred_foot": "Droitier",
        "position": "CM",
        "role": "M",
        "birth_date": "2004-09-27",
        "nationality": "Portugal",
        "photo": "https://images.fotmob.com/image_resources/playerimages/1283296.png",
        "notes": "Prodige portugais au cœur du jeu parisien"
    },
    {
        "player_name": "Désiré Doué",
        "from_team": "Rennes",
        "to_team": "PSG",
        "transfer_date": "2024-08-17",
        "season": "2024-2025",
        "mercato_window": "SUMMER",
        "transfer_type": "ACHAT_SEC",
        "transfer_type_label": "💰 Achat Définitif",
        "fee_numeric_eur": 50000000.0,
        "fee_display": "50.00 M€",
        "market_value_eur": 30000000.0,
        "market_value_display": "30.00 M€",
        "preferred_foot": "Droitier",
        "position": "LW",
        "role": "A",
        "birth_date": "2005-06-03",
        "nationality": "France",
        "photo": "https://images.fotmob.com/image_resources/playerimages/1283298.png",
        "notes": "Pépite française recrutée au Stade Rennais"
    },
    {
        "player_name": "Dani Olmo",
        "from_team": "RB Leipzig",
        "to_team": "FC Barcelona",
        "transfer_date": "2024-08-09",
        "season": "2024-2025",
        "mercato_window": "SUMMER",
        "transfer_type": "ACHAT_SEC",
        "transfer_type_label": "💰 Achat Définitif",
        "fee_numeric_eur": 55000000.0,
        "fee_display": "55.00 M€",
        "market_value_eur": 60000000.0,
        "market_value_display": "60.00 M€",
        "preferred_foot": "Droitier",
        "position": "AM",
        "role": "M",
        "birth_date": "1998-05-07",
        "nationality": "Espagne",
        "photo": "https://images.fotmob.com/image_resources/playerimages/585028.png",
        "notes": "Maestro de l'Euro 2024 de retour dans son club formateur"
    },
    {
        "player_name": "Leny Yoro",
        "from_team": "Lille",
        "to_team": "Manchester United",
        "transfer_date": "2024-07-18",
        "season": "2024-2025",
        "mercato_window": "SUMMER",
        "transfer_type": "ACHAT_SEC",
        "transfer_type_label": "💰 Achat Définitif",
        "fee_numeric_eur": 62000000.0,
        "fee_display": "62.00 M€",
        "market_value_eur": 50000000.0,
        "market_value_display": "50.00 M€",
        "preferred_foot": "Droitier",
        "position": "CB",
        "role": "D",
        "birth_date": "2005-11-13",
        "nationality": "France",
        "photo": "https://images.fotmob.com/image_resources/playerimages/1301072.png",
        "notes": "Espoir tricolore de la défense centrale mancunienne"
    },
    {
        "player_name": "Riccardo Calafiori",
        "from_team": "Bologna",
        "to_team": "Arsenal",
        "transfer_date": "2024-07-29",
        "season": "2024-2025",
        "mercato_window": "SUMMER",
        "transfer_type": "ACHAT_SEC",
        "transfer_type_label": "💰 Achat Définitif",
        "fee_numeric_eur": 45000000.0,
        "fee_display": "45.00 M€",
        "market_value_eur": 45000000.0,
        "market_value_display": "45.00 M€",
        "preferred_foot": "Gaucher",
        "position": "CB",
        "role": "D",
        "birth_date": "2002-05-19",
        "nationality": "Italie",
        "photo": "https://images.fotmob.com/image_resources/playerimages/1070257.png",
        "notes": "Défenseur moderne italien recruté à Arsenal"
    },
    {
        "player_name": "Teun Koopmeiners",
        "from_team": "Atalanta",
        "to_team": "Juventus",
        "transfer_date": "2024-08-28",
        "season": "2024-2025",
        "mercato_window": "SUMMER",
        "transfer_type": "ACHAT_SEC",
        "transfer_type_label": "💰 Achat Définitif",
        "fee_numeric_eur": 54700000.0,
        "fee_display": "54.70 M€",
        "market_value_eur": 55000000.0,
        "market_value_display": "55.00 M€",
        "preferred_foot": "Gaucher",
        "position": "AM",
        "role": "M",
        "birth_date": "1998-02-28",
        "nationality": "Pays-Bas",
        "photo": "https://images.fotmob.com/image_resources/playerimages/841281.png",
        "notes": "Meneur hollandais de la Juventus"
    },
    {
        "player_name": "Endrick",
        "from_team": "Palmeiras",
        "to_team": "Real Madrid",
        "transfer_date": "2024-07-21",
        "season": "2024-2025",
        "mercato_window": "SUMMER",
        "transfer_type": "ACHAT_SEC",
        "transfer_type_label": "💰 Achat Définitif",
        "fee_numeric_eur": 47500000.0,
        "fee_display": "47.50 M€",
        "market_value_eur": 60000000.0,
        "market_value_display": "60.00 M€",
        "preferred_foot": "Gaucher",
        "position": "ST",
        "role": "A",
        "birth_date": "2006-07-21",
        "nationality": "Brésil",
        "photo": "https://images.fotmob.com/image_resources/playerimages/1335028.png",
        "notes": "Phénomène brésilien au Real Madrid"
    },
    {
        "player_name": "Savinho",
        "from_team": "Troyes",
        "to_team": "Manchester City",
        "transfer_date": "2024-07-18",
        "season": "2024-2025",
        "mercato_window": "SUMMER",
        "transfer_type": "ACHAT_SEC",
        "transfer_type_label": "💰 Achat Définitif",
        "fee_numeric_eur": 25000000.0,
        "fee_display": "25.00 M€",
        "market_value_eur": 50000000.0,
        "market_value_display": "50.00 M€",
        "preferred_foot": "Gaucher",
        "position": "RW",
        "role": "A",
        "birth_date": "2004-04-10",
        "nationality": "Brésil",
        "photo": "https://images.fotmob.com/image_resources/playerimages/1148809.png",
        "notes": "Ailier virevoltant brésilien de City"
    }
]

print("=" * 75)
print(" 🚀 PEUPLEMENT DE LA TABLE DE FAITS ENRICHIE fct_player_transfers")
print("=" * 75)

conn = sqlite3.connect(DB_PATH)
cursor = conn.cursor()

# Get team logos from dim_teams if available
cursor.execute("SELECT team_id, name, logo_url, league_id FROM dim_teams;")
team_map = {}
for r in cursor.fetchall():
    team_map[r[1].lower()] = {'id': r[0], 'name': r[1], 'logo': r[2], 'league': r[3]}

inserted = 0
for trf in TRANSFERS_RAW:
    pname = trf["player_name"]
    from_t = trf["from_team"]
    to_t = trf["to_team"]
    tdate = trf["transfer_date"]
    
    flag, nat_code = COUNTRY_FLAGS.get(trf["nationality"], ('🌍', trf["nationality"][:3].upper()))
    
    from_meta = team_map.get(from_t.lower(), {
        'id': f"CLUB_{slugify(from_t).upper()}",
        'name': from_t,
        'logo': f"https://media.api-sports.io/football/teams/{abs(hash(from_t)) % 10000}.png",
        'league': LEAGUE_BY_TEAM.get(from_t, 'AUTRE')
    })
    
    to_meta = team_map.get(to_t.lower(), {
        'id': f"CLUB_{slugify(to_t).upper()}",
        'name': to_t,
        'logo': f"https://media.api-sports.io/football/teams/{abs(hash(to_t)) % 10000}.png",
        'league': LEAGUE_BY_TEAM.get(to_t, 'AUTRE')
    })
    
    # Calculate age at transfer
    b_date = trf.get("birth_date", "2000-01-01")
    try:
        t_yr = int(tdate[:4])
        b_yr = int(b_date[:4])
        age_at_trf = t_yr - b_yr
    except Exception:
        age_at_trf = 24

    pid = f"ply_{slugify(pname)}_{slugify(to_t)}"
    trf_id = f"trf_{slugify(pname)}_{slugify(from_t)}_{slugify(to_t)}_{tdate.replace('-', '_')}"
    
    fee_num = trf.get("fee_numeric_eur", 0.0)
    mv_num = trf.get("market_value_eur", fee_num)
    delta_num = fee_num - mv_num
    
    cursor.execute("""
        INSERT OR REPLACE INTO fct_player_transfers (
            transfer_id, player_id, player_name, player_display_name, player_position,
            player_role, player_nationality, player_nationality_code, player_nationality_flag,
            player_photo_url, from_team_id, from_team_name, from_team_logo, from_team_league,
            to_team_id, to_team_name, to_team_logo, to_team_league, transfer_date,
            season, mercato_window, transfer_type, transfer_type_label, fee_numeric_eur,
            fee_display, market_value_eur, market_value_display, fee_value_delta_eur,
            age_at_transfer, preferred_foot, transfer_notes
        ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
    """, (
        trf_id, pid, pname, pname, trf.get("position", "MC"),
        trf.get("role", "M"), trf.get("nationality", "France"), nat_code, flag,
        trf.get("photo"), from_meta['id'], from_meta['name'], from_meta['logo'], from_meta['league'],
        to_meta['id'], to_meta['name'], to_meta['logo'], to_meta['league'], tdate,
        trf.get("season", "2026-2027"), trf.get("mercato_window", "SUMMER"), trf.get("transfer_type", "ACHAT_SEC"),
        trf.get("transfer_type_label", "💰 Achat Définitif"), fee_num, trf.get("fee_display", "0 €"),
        mv_num, trf.get("market_value_display", "0 €"), delta_num,
        age_at_trf, trf.get("preferred_foot", "Droitier"), trf.get("notes", "")
    ))
    inserted += 1

conn.commit()

# Report stats by season
cursor.execute("SELECT season, count(*), sum(fee_numeric_eur) FROM fct_player_transfers GROUP BY season ORDER BY season DESC;")
stats = cursor.fetchall()
conn.close()

print(f"===========================================================================")
print(f"🎉 SUCCÈS : {inserted} transferts enrichis enregistrés dans fct_player_transfers !")
print("   Répartition par saison :")
for s, count, total_fee in stats:
    print(f"   ├─ Saison {s} : {count} transferts | Volume total : {(total_fee or 0)/1000000:.1f} M€")
print("===========================================================================")
